In [1]:
from models.encoderRNN import EncoderRNN
from models.decoderRNN import DecoderRNN
from models.seq2seq import Seq2seq
enc = EncoderRNN(80, 256,
                     input_dropout_p = 0.5, dropout_p = 0.5,
                     n_layers = 5,
                     bidirectional = True, rnn_cell = 'gru', variable_lengths = False)

dec = DecoderRNN(2040, 80, 256 * 2,
                     2037, 2038,
                     layer_size = 3, rnn_cell = 'gru', bidirectional = True,
                     input_dropout_p = 0.5, dropout_p = 0.5, use_attention = True)

model = Seq2seq(enc, dec)
model

Seq2seq(
  (encoder): EncoderRNN(
    (input_dropout): Dropout(p=0.5, inplace=False)
    (conv): Sequential(
      (0): Conv2d(1, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (1): Hardtanh(min_val=0, max_val=20, inplace=True)
      (2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (3): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (4): Hardtanh(min_val=0, max_val=20, inplace=True)
      (5): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (6): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (7): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (8): Hardtanh(min_val=0, max_val=20, inplace=True)
      (9): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (10): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
 

In [6]:
import numpy as np
feat = np.arange(33*10).reshape(33,10)
print(feat)
np.ascontiguousarray(np.swapaxes(feat[:,::-1],0,1))

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]
 [200 201 202 203 204 205 206 207 208 209]
 [210 211 212 213 214 215 216 217 218 219]
 [220 221 222 223 224 225 226 227 228 229]
 [230 231 2

array([[  9,  19,  29,  39,  49,  59,  69,  79,  89,  99, 109, 119, 129,
        139, 149, 159, 169, 179, 189, 199, 209, 219, 229, 239, 249, 259,
        269, 279, 289, 299, 309, 319, 329],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98, 108, 118, 128,
        138, 148, 158, 168, 178, 188, 198, 208, 218, 228, 238, 248, 258,
        268, 278, 288, 298, 308, 318, 328],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97, 107, 117, 127,
        137, 147, 157, 167, 177, 187, 197, 207, 217, 227, 237, 247, 257,
        267, 277, 287, 297, 307, 317, 327],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96, 106, 116, 126,
        136, 146, 156, 166, 176, 186, 196, 206, 216, 226, 236, 246, 256,
        266, 276, 286, 296, 306, 316, 326],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115, 125,
        135, 145, 155, 165, 175, 185, 195, 205, 215, 225, 235, 245, 255,
        265, 275, 285, 295, 305, 315, 325],
       [  4,  14,  24,  34,  44,  54,  64,  74,  8