In [1]:
import numpy as np
import pandas as pd

In [7]:
train_list_audio = pd.read_csv("train_list.csv", encoding='utf-8', delimiter=',')["audio"]
test_list_audio = pd.read_csv("test_list.csv", encoding="utf-8", delimiter=',')["audio"]
train_list_label = pd.read_csv("train_list.csv", encoding='utf-8', delimiter=',')["label"]
test_list_label = pd.read_csv("test_list.csv", encoding="utf-8", delimiter=',')["label"]

In [8]:
audio_paths = list(train_list_audio) + list(test_list_audio)
label_paths = list(train_list_label) + list(test_list_label)

In [9]:
audio_paths[:5]

['KaiSpeech_078903.pcm',
 'KaiSpeech_449461.pcm',
 'KaiSpeech_620819.pcm',
 'KaiSpeech_103058.pcm',
 'KaiSpeech_420656.pcm']

In [10]:
label_paths[:5]

['KaiSpeech_label_078903.txt',
 'KaiSpeech_label_449461.txt',
 'KaiSpeech_label_620819.txt',
 'KaiSpeech_label_103058.txt',
 'KaiSpeech_label_420656.txt']

In [13]:
import random
tmp = list(zip(audio_paths, label_paths))
random.shuffle(tmp)
audio_paths, label_paths = zip(*tmp)

In [21]:
total_num = len(audio_paths)     # 1,000h
test_num = int(total_num * 0.02) # 1,000h x 0.02 = 20h
train_num = total_num - test_num
print(total_num)
print(test_num)
print(train_num)

646632
12932
633700


In [22]:
train_dict = {"audio" : [], "label" : []}
test_dict = {"audio" : [], "label" : []}
train_dict["audio"] = audio_paths[:train_num]
test_dict["audio"] = audio_paths[train_num:]
train_dict["label"] = label_paths[:train_num]
test_dict["label"] = label_paths[train_num:]

In [25]:
print(len(train_dict["audio"]))
print(len(train_dict["label"]))
print(len(test_dict["audio"]))
print(len(test_dict["label"]))

633700
633700
12932
12932


In [26]:
train_df = pd.DataFrame(train_dict)
test_df = pd.DataFrame(test_dict)

In [33]:
train_df.head()

audio                       label
0  KaiSpeech_103762.pcm  KaiSpeech_label_103762.txt
1  KaiSpeech_126833.pcm  KaiSpeech_label_126833.txt
2  KaiSpeech_367790.pcm  KaiSpeech_label_367790.txt
3  KaiSpeech_005465.pcm  KaiSpeech_label_005465.txt
4  KaiSpeech_133374.pcm  KaiSpeech_label_133374.txt

In [34]:
test_df.head()

audio                       label
0  KaiSpeech_311808.pcm  KaiSpeech_label_311808.txt
1  KaiSpeech_561767.pcm  KaiSpeech_label_561767.txt
2  KaiSpeech_277694.pcm  KaiSpeech_label_277694.txt
3  KaiSpeech_248124.pcm  KaiSpeech_label_248124.txt
4  KaiSpeech_404513.pcm  KaiSpeech_label_404513.txt

In [35]:
train_df.to_csv("train_list.csv", encoding="cp949", index=False)
test_df.to_csv("test_list.csv", encoding="cp949", index=False)

In [37]:
print(len(train_df))
print(len(test_df))

633700
12932


In [39]:
import torch
test = torch.FloatTensor([1,2,3,4,5])

In [40]:
test

tensor([1., 2., 3., 4., 5.])

In [41]:
torch.stack(test, dim=1)

TypeError: stack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

In [42]:
a = 7
b = 5
print( *divmod(a, b) )

1 2


In [59]:
test = torch.Tensor([1,2,3,4,5,6,7,8,9])
len(test)

9

In [58]:
int(test[2])

3

In [48]:
test // 5

tensor([0., 0., 0., 0., 1., 1., 1., 1., 1.])

In [60]:
test = [1, 2, 2, 3, 4, 5, 5, 6]

In [61]:
del test[0]
test

[2, 2, 3, 4, 5, 5, 6]

In [63]:
test = [1,2,3,4,5]
sorted(test, reverse=True)

[5, 4, 3, 2, 1]

In [64]:
a = [1,2,3,4,5]
b = ['a','b','c','d','e']
tmp = zip(a, b)
a, b = zip(*sorted(tmp, reverse=True))

In [65]:
a

(5, 4, 3, 2, 1)

In [66]:
b

('e', 'd', 'c', 'b', 'a')

In [69]:
test = torch.FloatTensor([[1,2,3,4,5], [4,5,6,7,8]])
torch.cat((test[0], test[1]), dim = 0)

tensor([1., 2., 3., 4., 5., 4., 5., 6., 7., 8.])

In [71]:
test = torch.FloatTensor([0]*8)

In [74]:
test[0] = torch.FloatTensor([0]*8)

RuntimeError: expand(torch.FloatTensor{[8]}, size=[]): the number of sizes provided (0) must be greater or equal to the number of dimensions in the tensor (1)

In [79]:
all(torch.Tensor([1,1,1,1,1,1]) == torch.Tensor([1,1,1,0,1,1]))

False