In [2]:
from utils.load import *
from utils.define import *
audio_paths, label_paths = load_data_list(data_list_path=TRAIN_LIST_PATH, dataset_path=DATASET_PATH)
target_dict = load_targets(label_paths)

[2020-02-23 02:22:44,973 utils.py:141 - _init_num_threads()] NumExpr defaulting to 8 threads.


100%|████████████████████████████████████████████████████████████████████████| 633698/633698 [01:27<00:00, 7230.61it/s]


In [3]:
len(target_dict)

610589

In [33]:
import numpy as np

for idx, item in enumerate(target_dict.items()):
    tmp = item[1].split()
    tmp = np.array(tmp).astype('int')
    if any(tmp < 0) or any(tmp > 2039):
        print(tmp)

[  35   11    0   98   66    0  131    0    2   48    0  107    3    0
   94   23    6  152    0   98   66    0    7  264    3  107   21    0
  173 2083    3  107    1]
[ 193    6    0    3  450    0  143  241    0   46   36   29   18    0
   71  100    0  129   12    0 2048    0  135   21    0   88    0    5
   20   24    0   65   21    0   88   12]
[2164   54    0  111   10    1    0   30   16]
[  82   33    0   10   13    6   15    6    0  161  656   16    0    3
    9    0   34    7    0  137    8   16    0    3    9    0   37    0
   34   24    0  313  210   14    4    0    9   25    1    0   29    0
 2243   98   17    0   40    0   41    6    0  151   31    0  496   15
    7    0   14   24   23    0    2   15   83    0  197   17    0  184
    3    0   76   53   24    0  126    0   34    4    0    9    7]
[   2   73    0   40    0  183  484    3   20   29    0   27    0   77
   39    0   65   18    0   26    7    0    5   20   24    0   41    6
    0   42   22   17    4    0    2 

    3    9    4    0  103    0  105  114   85    8    1]
[  49   18    0   59   43    0  101    0  334  151   20  254   17    0
  104  335   96    1    0  101    0   43  284    0    5    0   49   95
    0   39    0  155    0  124   37    0   15  485   16    0  334  151
   20  254    3   13    0  192 2144   18    0   36    8  181    0  146
    3    0   76    8    0   54   74    1]
[  35   11    0   34    7    6    0  120    0  661   64   15    4    0
    9   25    1    0    2    9    0  383   63    0   54   74    0    5
    0   13    4    0  128   42   15    0  459    0  126    0   64    4
   11    0    8 2075   19    0   41    6    0  175   92   28    0   14
   13   21    0  160  370    0  166   18    0   10   88    0   76   10
   46    1]
[  86    0    2 2328    0   13    3    0  134   95    0   59   34   18
    0   37    0   14    9   89   12    0   49   18    0   37    0   14
   10    0  111  117   12    0   46   13   18   12    0    5    0   30
   12]
[  49    0  141    0 2298    0

  137   23    0   11    6    0   76   53   20   29    1]
[ 105  114   85    8    1    0    2   33   16    0    5   20   21    0
   13    4    0  284   21    0  131    0   90  153   70 2093    0  246
    0  102  139    9   89    0  221  147  110   21    0  132   70   18
    0   90  153   70  331   55    0   71  100   64    7]
[   2  164    0   40    0   43    6    0  428   65   78  115   17   16
    0   45  519    0   64  113    0  859    0 2059   20   15   21    0
    3   33   12]
[   2   19    0   94   23    0    9    0   44   67    1    0    2  330
    0    2   58   24    0    3   43    0   68   31    0   13   32   18
    0  177  393   29   10    0   22  166   55    0  672    0 2258    8
    0  343   53   24   23]
[   5    0    2 2255   12]
[   2   58    7    0  140   17    4    0  494    0  228    0   47   17
    0 2280]
[   2   99    0  112  144    0   30    1    0   54   74    0    2    9
    0  118   33  530    0  271   36    3   22    0  495    0  152    0
   35   11    0   41  

   50   30   16    0    8  234   19    0   71  100   28    0   30   12]
[  35   11    0   60    0   39  396    3   32    0   30   18    0   60
    0   54   74    0  508    0 2155   22    7    0   60    0    3   48
    0   39  396    3    0    5   20   32    0    2   73    0   57  275
    0    2    0  400  386   12    0    3   48    0  106   18    0   26
   13    0  152    1    0   68   31    0  188   17   16    1    0    2
   33   16    0    2   73    0   60    0   59  339    3    0   90  401
   27    0  106    0   44    5    1    0    2   20   29    0   60    0
   70    3  238    0  299   15    0   75    7    0   60    0   60    0
  294    0  747   15    0  262    7   12    0    2   48    0    9   12]
[   5    0  163  363   50  576   14    7    0   15    0  133    8   21
    0  105   89    0  358    0   15    0  133    8    1    0    2    0
   15    0   30    6   10    7    0   27    0  187  282  156   17    0
   15 2189    5    0  228  163    0  168    0  228  163    0  168    0
   3

   74    1]
[ 242  130  205    0  288  106  301    0 2125    3   24    0   54   74
    0   81    3    0  195    5    1]
[  13   21    0  774  253    0    6   16    0  885 2210   13  203    9
   89   12    0   68   31    4    0   16  230   68  177    0   87   56
    5    1    0   49    0   16  230    0   68  177   17    0   50   30
   16    0    8  234   19    0   71  100   30   12]
[   5    0  131    0  124    5   31    0   91    0    9   25    1    0
    8    0  124    5   31    0   91    0    9   25    1    0    5    0
    8    1    0  156 2146    0   30   25   10    1    0   91    0   99
    0   81    5   21    0   13    1    0   91    0   99    0   81    5]
[   8    0 2060    0    5    0   47    0   77  307  413    1]
[ 102  116   30   16    0   41   22   18    0 2207    0  187  574   64
   10    1    0   41    6    0    2   51    0   25   66   17    0  239
   33  183    0  102  116   14   24   16]
[ 140   17    0  158    6    0  191    6    0   49   61    0    7  247
    6  462   

    1    0    2   33   16    0   40]
[   3   93   17    4    0   41    6    0  133   28    0   51    4    0
  204  329    3    0   94   10    0  111    5    1    0  171    0  168
  130    0 2200    3   25   21    0   10   88    1]
[  35   11    0  374  196   53   38    0   47  226   14    4    0    9
    4    0  509   46    0    2   33   18    0   70   10   60    0   45
  584  200    3    0   26   10    1    0  464 2192   11    1    0    8
  190    0    6   16    0  131   15  144   15   64    4   11    0    2
   33   18    1]
[   2   11    0    2    0 2106    4    0   34   97   18    0  405  144
   15    1    0  229  435    0   15    0   13  206    0   84   18   38
    0  320   62   53   24    0   52   19    0    6   29    3    0  206
   31  349  150    0   37   17   16    0  320   23    0    9    0    5
   20   25   12]
[ 134   96   36    0   35  453   23    0    2   51    0   77   64  574
    3    0  233    9    0   76    8   69    1    0  161   55    0   36
    8   16    0   41    6

  175  124  391   20   15    1]
[  13    0    3   93   17    0  122  122 2251    0  122  122   95    0
   70   79  220   32   18    0   15    0  537    8    1]
[ 112    8    0  112    8    1    0    2    0  102 1089   39    0   26
    4    0  104    0   87    7    0  137   62    4   11    0    2    0
  221    0    9   22   17    0    3   43    0   35   11    0  291  148
  110    0   15    0  150    8   38    0  159    0    3  223    0   52
    8    0   26    7    0  828  189   79   18    0  828 2174   79    0
    3   72   19    0   52    8    0   26    7    0   60    0  302 1058
    0   60    0  483   13   15    0  302 1058  212  162    0    3   72
   19    0   14   24   16    0   60    0  150    8   38    0   15    0
   52    8    0   26    4   11    0    9   22   17    0    3   43    0
  165  296   18]
[  60    0  318    0   50    0 2333    0  448   63  109    0    3   48
    0    9    0   46   36    8    0  343    7    1    0  296  166  109
    0  441   17   15    6    1    0   60  

   73    0    2   33   18    0   26    4    0  106    0   44    5    1]
[   2   73    0    2   51    4    0   14  323    0  217    0    2    0
   41    0   71   39    3    0  119    0  280    0   39   59   11    0
    5   70    0    2   51    6    0   39   69   39   59    6    0    2
  180    8    1    0    2   10    0   35   11    0   88   69   39   17
    0 2179   17   16    0  931    0  169    0   75  155   59    6    0
   34    0   75  155    0  247  307   55    0   64    7   21]
[ 136    0  122  266   96   12    0 2238   83  295   23   12]
[  35   11    0  246    3    0  176    0  324   31    0   15 2166  113
    0    9    0   44   67    1    0  806  464    3    0   52   19    0
  226    7    0  806  464    3    0   71  100   42   15    0   81    5
    1]
[   5    0    6    0   19  255   28    0   40    0    3   72   19    0
  142  178    0  663   22    4    0   99    0    5  292   11    0  289
   22  200    3    0  107   22   24   23    0    2   51    0    2   51
   70   15    0 

   51    0   10  230    0    9    0   44   23   11    1]
[ 377    6  130    0  640 2042   20   15    1]
[  88    0   15    0  104    8   15 2297    8   12]
[   9    0  127  504   17    0    9    0    5    0   86  290   17    0
   80  212    6   10    7    0    9    0   63   41   49 1181   70    0
    9    0   47    0   90  189    0  433    7    6    0    3    0  752
   28    0  247    6   10    7    0 2236   28  545    0    3  223    0
   30    6   10    7    0   90   47    0  433    7   55    0    9    0
  582   17    0  422    8  599    1]
[2161    0  229   70    0   84   18    0   14  117   12]
[   2   33   16    0   13    0   19    6    0   87    7    0  137    8
    6   10    7    0    9   22    0    8  190   10   12    0  116    3
  627   12    0    2    0  387  149   17    0   26    4   11    0   26
   56    5    0    2    0  976   79  185    0 2090    0  220  334    0
    5   20    7    0  976   79  185    0   90  334    0   35   11    0
   49   61    0  122  266   16    0  126

 2195    0   40   40    0   69   48    0  204  329    3   62    4   11]
[ 309    0 2309   12    0  309    0 1628  222   56    5    1    0  583
   38  262  307]
[   2    0   90  153    3    0  101    0    5  507  144    0   27    0
    9    0   44   67    1    0  141  117   24    0   16  121   32    4
    0  106   28    0   22  215   53   38    0   75   43   55    0   84
   30   16    0   92   47   55    0  228   62    4   11    0    2    0
   90  153    3    0  187  281   26   53   20   29    0   34  149   23
    0    2   73    0  285 2322  603   46    0   42    7    0  267    0
   65  293   17    0   76   56    5   69    1]
[  14   13  293   17    0   40    0 2168    8    1    0    2   51    0
  217    0   27  288   11    0  296  265    1    0    9   22  293   17
    0   76   56    5    1]
[ 185    7   13    4    0    9   10    0    3    9    0  507   10    0
  111    5    1    0   49    6    0    3 2085    0   60    0   14   68
    0  712    0   26    4    0   19    0    5   20   25 

   63  248    0  168    0  156 1021   12]
[  68   10   17    0  109   60   21    0   41    6    0   40    6    0
  272   10    0  105  114    7   21    0   41    6    0  227   63   59
   10    0  105  114    7   21    0  127    4    0    2   19    0   34
  210   55    0  143  376   14   19    0   46   36    0   65    0   26
   15    7    0   71  100   30   69    1    0  185   45   55    0   71
  100   14    4    0  106   18    0  285  170   21    0  185   45   55
    0   71  100   14    4    0 2324   18    0  285  170    0   45   22
   55    0   71  100   14    4    0    9   21    0    2    3   29    0
    3  185  146    0    3    0    3  185  146   59    0  106  211  166
   18    0  127    4    0    3   22  146   59    0  106   17   16    0
   22   59   27   15    7    0   71  100   14   22    0   51  157   17
    1]
[  63   32   25    1    0    9  581   77    3   25    1    0  260  324
   66    0   14    0  173    0   49    4    0  173    0  101    0 1050
   25    0  159    1    0  2